import os
import io
import json
import dash
import base64
import httplib2
import google_auth_httplib2
from datetime import datetime
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseUpload
import dash_bootstrap_components as dbc
from dotenv import load_dotenv
from dash import html, dcc, Input, Output, ALL, State, MATCH, ClientsideFunction

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(BASE_DIR, "assets", "config.json")

possible_env_paths = [
    os.path.join(BASE_DIR, "secrets", ".env"),
    os.path.join(BASE_DIR, ".env"),
    "/home/mtpocketstheatre/secrets/.env",
    os.path.expanduser("~/secrets/.env")
]

env_loaded = False
for env_path in possible_env_paths:
    if os.path.exists(env_path):
        load_dotenv(env_path)
        print(f"Loaded environment variables from: {env_path}")
        env_loaded = True
        break

if not env_loaded:
    print("Warning: Could not find a .env file in expected locations.")

IS_PRODUCTION = (
    os.environ.get("PYTHONANYWHERE_SITE") is not None
    or os.environ.get("APP_ENV") == "production"
)
REQUESTS_PREFIX = '/pageant/' if IS_PRODUCTION else '/'

# Load configuration generated by update_event.py
def load_config():
    config_path = os.path.join("assets", "config.json")
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "title": "MT Pockets Pageant Registration",
        "description": "",
        "base_fee": 50.0,
        "flyer_image": "flyer.jpg",
        "info_sections": [],
        "divisions": [],
        "addons": [],
        "form_fields": [],
        "disclaimer": None
    }

# Load configuration with fallback
EVENT_CONFIG = {}
if os.path.exists(CONFIG_PATH):
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        EVENT_CONFIG = json.load(f)
else:
    print(f"WARNING: Configuration file not found at {CONFIG_PATH}")

# PayPal Client ID
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID", "test")

GOOGLE_SCOPES = [
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/spreadsheets"
]

app = dash.Dash(
    __name__,
    requests_pathname_prefix=REQUESTS_PREFIX,
    routes_pathname_prefix='/',
    external_stylesheets=[
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    ],
    external_scripts=[
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
        f"https://www.paypal.com/sdk/js?client-id={PAYPAL_CLIENT_ID}&currency=USD"
    ]
)

server = app.server

app.title = EVENT_CONFIG.get("title", "MT Pockets Pageant Registration")

# --- HELPER RENDER FUNCTIONS ---

def render_event_info(config):
    """Renders info_sections with the first section expanded by default."""
    info_sections = config.get("info_sections", [])
    if info_sections:
        accordion_items = []
        for idx, sec in enumerate(info_sections):
            accordion_items.append(
                html.Details(
                    className="mb-2 border rounded overflow-hidden bg-white shadow-sm",
                    open=(idx == 0),  # General Information / 1st section starts OPEN
                    children=[
                        html.Summary(
                            sec.get("title", f"Section {idx+1}"),
                            className="fw-bold p-3 bg-light text-dark",
                            style={"cursor": "pointer", "userSelect": "none"}
                        ),
                        html.Div(
                            sec.get("content", ""),
                            className="p-3 border-top",
                            style={"whiteSpace": "pre-line", "lineHeight": "1.6"}
                        )
                    ]
                )
            )
        return html.Div(className="accordion-container", children=accordion_items)

    return html.Div(
        config.get("description", ""),
        style={"whiteSpace": "pre-line", "lineHeight": "1.6"}
    )

def render_dynamic_form_fields(fields):
    """
    Renders dynamic form fields with expanded input controls (email, date, tel, file upload)
    and standardized pattern-matching IDs for pre-payment validation.
    """
    components = []

    for f in fields:
        field_id = f["id"]
        label_text = f["label"]
        is_required = f.get("required", False)
        field_type = f.get("type", "text")

        # Required field visual indicator (*)
        label_children = [
            label_text,
            html.Span(" *" if is_required else "", style={"color": "red", "fontWeight": "bold"})
        ]

        field_children = [
            html.Label(label_children, className="form-label fw-bold mt-2")
        ]

        if f.get("description"):
            field_children.append(html.P(f["description"], className="small text-muted mb-1"))

        # Derive placeholder text
        clean_label = label_text.split("(")[0].replace("*", "").strip()
        placeholder_text = f.get("placeholder", f"Enter {clean_label}...")

        # 1. Contact Email Input
        if field_type == "email":
            field_children.append(
                dbc.Input(
                    id={"type": "form-input", "id": field_id},
                    type="email",
                    placeholder="name@example.com",
                    className="form-control w-100"
                )
            )

        # 2. Date of Birth Input
        elif field_type == "date":
            field_children.append(
                dbc.Input(
                    id={"type": "form-input", "id": field_id},
                    type="date",
                    className="form-control w-100"
                )
            )

        # 3. Phone Number Input
        elif field_type == "tel":
            field_children.append(
                dbc.Input(
                    id={"type": "form-input", "id": field_id},
                    type="tel",
                    placeholder="(304) 555-0123",
                    className="form-control w-100"
                )
            )

        # 4. Headshot Photo Upload Component
        elif field_type == "file":
            field_children.append(
                html.Div([
                    dcc.Upload(
                        id={"type": "form-upload", "id": field_id},
                        children=html.Div([
                            "Drag & Drop or ",
                            html.A("Select Headshot Photo", style={"color": "var(--mt-primary)", "fontWeight": "bold"})
                        ]),
                        style={
                            "width": "100%",
                            "height": "64px",
                            "lineHeight": "64px",
                            "borderWidth": "2px",
                            "borderStyle": "dashed",
                            "borderRadius": "8px",
                            "textAlign": "center",
                            "backgroundColor": "#f8f9fa",
                            "cursor": "pointer"
                        },
                        multiple=False
                    ),
                    html.Div(id={"type": "upload-status", "id": field_id}, className="mt-2 text-muted small")
                ])
            )

        # 5. Multiline Text Area
        elif field_type == "textarea":
            field_children.append(
                dcc.Textarea(
                    id={"type": "form-input", "id": field_id},
                    className="form-control w-100",
                    rows=3,
                    placeholder=placeholder_text
                )
            )

        # 6. Dropdown Options
        elif field_type == "dropdown":
            field_children.append(
                dcc.Dropdown(
                    id={"type": "form-input", "id": field_id},
                    options=[{"label": opt, "value": opt} for opt in f.get("options", [])],
                    clearable=not is_required,
                    className="w-100 mb-2",
                    placeholder=f"Select {clean_label}..."
                )
            )

        # 7. Radio Buttons
        elif field_type == "radio":
            field_children.append(
                dbc.RadioItems(
                    id={"type": "form-input", "id": field_id},
                    options=[{"label": opt, "value": opt} for opt in f.get("options", [])],
                    className="custom-radio-group mb-2"
                )
            )

        # 8. Standard Text Input Fallback
        else:
            field_children.append(
                dcc.Input(
                    id={"type": "form-input", "id": field_id},
                    type="text",
                    className="form-control w-100",
                    placeholder=placeholder_text
                )
            )

        components.append(html.Div(className="mb-3", children=field_children))

    return components

def render_addons_section(addons):
    """Renders optional categories (Themewear, Talent, Photogenic, etc.)"""
    if not addons:
        return None

    addon_cards = []
    for addon in addons:
        options_list = [
            {"label": f" {opt['label']}", "value": opt['label']}
            for opt in addon.get("options", [])
        ]

        default_val = addon["options"][0]["label"] if addon.get("options") else None
        for opt in addon.get("options", []):
            if opt["label"].lower() in ["no", "none", "no thanks", "i do not wish to enter"]:
                default_val = opt["label"]
                break

        addon_cards.append(
            html.Div(className="mb-4 pb-3 border-bottom", children=[
                html.H6(addon.get("title", "").split("\n")[0], className="fw-bold text-dark mb-1"),
                html.P(addon.get("description"), className="small text-muted mb-2", style={"whiteSpace": "pre-line"}),
                dcc.RadioItems(
                    id={'type': 'addon-select', 'index': addon.get("id", sanitize_id(addon.get("title", "")))},
                    options=options_list,
                    value=default_val,
                    className="custom-radio-group"
                )
            ])
        )

    return html.Div(className="card card-custom mb-4", children=[
        html.Div(className="card-header card-header-secondary", children=[
            html.H5("Optional Categories & Add-Ons", className="mb-0 fs-5")
        ]),
        html.Div(className="card-body", children=addon_cards)
    ])

def render_disclaimer(disclaimer_data):
    """Renders rules & disclaimer agreement card"""
    if not disclaimer_data:
        return html.Div(dcc.RadioItems(id="disclaimer-agreement", style={"display": "none"}), style={"display": "none"})

    raw_title = disclaimer_data.get("title", "")
    text = disclaimer_data.get("text", "")

    if not raw_title or len(raw_title) > 80 or "\n" in raw_title or raw_title == text:
        header_title = "Pageant Rules & Sportsmanship Disclaimer"
    else:
        header_title = raw_title

    return html.Div(className="card card-custom disclaimer-card mb-4", children=[
        html.Div(className="card-header card-header-disclaimer p-3", children=[
            html.H5(header_title, className="mb-0 fs-5")
        ]),
        html.Div(className="card-body", children=[
            html.Div(
                text,
                className="disclaimer-full-text mb-3",
                style={"whiteSpace": "pre-line"}
            ),
            dcc.RadioItems(
                id="disclaimer-agreement",
                options=[{"label": f" {opt}", "value": opt} for opt in disclaimer_data.get("options", [])],
                className="custom-radio-group"
            )
        ])
    ])

def sanitize_id(title):
    import re
    clean = re.sub(r'[^a-zA-Z0-9\s]', '', title).strip().lower()
    return re.sub(r'\s+', '_', clean)

# --- APP LAYOUT ---

app.layout = html.Div(children=[

    # Form Validation & Transaction Completion Stores
    dcc.Store(id="payment-validation-store"),
    dcc.Store(id="transaction-completed-store", data=False),
    dcc.Store(id="paypal-transaction-store"),

    # 1. Header Banner
    html.Div(className="pageant-header text-center mb-4 py-4", children=[
        html.Div(className="container", children=[
            html.H1(EVENT_CONFIG.get("title", "Pageant Registration"), className="display-6 fw-bold mb-1"),
            html.P("M.T. Pockets Theatre, Inc. Fundraiser Registration", className="lead mb-0")
        ])
    ]),

    html.Div(className="container pb-5", children=[

        # 2. Hero Section: Flyer + Event Details Accordion
        html.Div(className="row g-4 mb-5", children=[
            html.Div(className="col-lg-5", children=[
                html.Div(className="flyer-card", children=[
                    html.Img(
                        src=app.get_asset_url(EVENT_CONFIG.get("flyer_image", "flyer.jpg")),
                        className="flyer-img",
                        alt="Event Flyer"
                    )
                ])
            ]),
            html.Div(className="col-lg-7", children=[
                html.Div(className="card card-custom h-100", children=[
                    html.Div(className="card-header card-header-primary", children=[
                        html.H5("Event Details & Information", className="mb-0 fs-5")
                    ]),
                    html.Div(className="card-body event-description-box", children=[
                        render_event_info(EVENT_CONFIG)
                    ])
                ])
            ])
        ]),

        # 3. Main Registration & Checkout Section
        html.Div(id="main-registration-container", children=[

            # Success / Reset Confirmation Banner (Hidden by default)
            html.Div(
                id="success-reset-row",
                className="row justify-content-center my-4",
                style={"display": "none"},
                children=[
                    html.Div(className="col-lg-8 text-center", children=[
                        html.Div(className="card card-custom p-5 shadow-sm border-0", children=[
                            html.Div(className="mb-4", children=[
                                html.H2("🎉 Registration Complete!", className="fw-bold text-success mb-3"),
                                html.P(
                                    "Thank you! Your pageant registration and payment have been successfully submitted.",
                                    className="lead text-secondary mb-0"
                                )
                            ]),
                            html.Div(children=[
                                dbc.Button(
                                    "Submit another registration",
                                    id="reset-registration-btn",
                                    color="primary",
                                    size="lg",
                                    className="px-4 py-2 fw-bold"
                                )
                            ])
                        ])
                    ])
                ]
            ),

            # Registration Form and Checkout Columns (Visible by default)
            html.Div(
                id="form-and-checkout-row",
                className="row g-4",
                children=[

                    # Left Column (lg-8): Form
                    html.Div(className="col-lg-8", children=[

                        # Participant Details Card
                        html.Div(className="card card-custom mb-4", children=[
                            html.Div(className="card-header card-header-primary", children=[
                                html.H5("1. Contestant & Contact Information", className="mb-0 fs-5")
                            ]),
                            html.Div(className="card-body", children=render_dynamic_form_fields(EVENT_CONFIG.get("form_fields", [])))
                        ]),

                        # Age Division Selection Card
                        html.Div(className="card card-custom mb-4", children=[
                            html.Div(className="card-header card-header-primary", children=[
                                html.H5("2. Select Age Division *", className="mb-0 fs-5")
                            ]),
                            html.Div(className="card-body", children=[
                                html.P(f"Main Event Entry Fee: ${EVENT_CONFIG.get('base_fee', 50.0):.2f}", className="small fw-bold text-muted mb-2"),
                                dcc.Dropdown(
                                    id="division-select",
                                    options=[
                                        {"label": f"{div['label']} — ${div['price']:.2f}", "value": div['label']}
                                        for div in EVENT_CONFIG.get("divisions", [])
                                    ],
                                    value=EVENT_CONFIG["divisions"][0]["label"] if EVENT_CONFIG.get("divisions") else None,
                                    clearable=False,
                                    className="form-select-lg"
                                )
                            ])
                        ]),

                        # Optional Add-Ons Section
                        render_addons_section(EVENT_CONFIG.get("addons", [])),

                        # Rules & Disclaimer Agreement Card
                        render_disclaimer(EVENT_CONFIG.get("disclaimer"))
                    ]),

                    # Right Column (lg-4): Sticky Checkout Summary & Payment
                    html.Div(className="col-lg-4", children=[
                        html.Div(className="sticky-top", style={"top": "20px"}, children=[
                            html.Div(className="card checkout-card p-4 text-center mb-3", children=[
                                html.H5("Registration Summary", className="text-uppercase tracking-wide text-white-50 mb-2 fs-6"),

                                # Fee Breakdown Output
                                html.Div(id="fee-breakdown-display", className="text-start mb-3 small text-white-50 border-bottom border-secondary pb-2"),

                                # Fee Total Display
                                html.Div("Total Amount Due", className="small text-uppercase text-white-50 fw-semibold"),
                                html.Div(id="fee-total-display", className="total-amount-display my-1", children="$50.00"),

                                # Dynamic Status Banner
                                html.Div(id="payment-notice-display", className="my-3"),

                                # Mount Point for PayPal Smart Payment Buttons
                                html.Div(id="paypal-button-container", style={"minHeight": "150px"}),

                                # Hidden Status Output for Clientside Callback
                                html.Div(id="paypal-mount-status", style={"display": "none"})
                            ]),

                            html.Div(className="text-center text-muted small", children=[
                                "M.T. Pockets Theatre, Inc. is a registered 501(c)(3) non-profit organization."
                            ])
                        ])
                    ])
                ]
            )
        ])
    ])
])

# --- DYNAMIC FEE CALCULATION CALLBACK ---

@app.callback(
    Output("fee-total-display", "children"),
    Output("fee-breakdown-display", "children"),
    Input("division-select", "value"),
    Input({'type': 'addon-select', 'index': ALL}, 'value')
)
def calculate_total_fee(selected_division, selected_addons):
    total = 0.0
    breakdown_items = []

    for div in EVENT_CONFIG.get("divisions", []):
        if div["label"] == selected_division:
            total += div["price"]
            breakdown_items.append(
                html.Div(className="d-flex justify-content-between mb-1", children=[
                    html.Span(f"Main Event ({selected_division}):", className="text-truncate me-2"),
                    html.Span(f"${div['price']:.2f}", className="fw-bold text-white")
                ])
            )
            break

    addons_config = EVENT_CONFIG.get("addons", [])
    if selected_addons and len(selected_addons) == len(addons_config):
        for addon_group, selected_val in zip(addons_config, selected_addons):
            if not selected_val:
                continue
            for opt in addon_group.get("options", []):
                if opt["label"] == selected_val:
                    if opt.get("price", 0) > 0:
                        total += opt["price"]
                        short_title = addon_group.get("title", "").split("\n")[0]
                        breakdown_items.append(
                            html.Div(className="d-flex justify-content-between mb-1", children=[
                                html.Span(f"{short_title}:", className="text-truncate me-2", style={"maxWidth": "180px"}),
                                html.Span(f"${opt['price']:.2f}", className="fw-bold text-white")
                            ])
                        )
                    break

    return f"${total:.2f}", breakdown_items

# --- FORM & DISCLAIMER VALIDATION CALLBACK ---

@app.callback(
    Output("payment-validation-store", "data"),
    Output("payment-notice-display", "children"),
    Input({"type": "form-input", "id": ALL}, "value"),
    Input({"type": "form-upload", "id": ALL}, "contents"),
    Input("division-select", "value"),
    Input("disclaimer-agreement", "value"),
    Input("fee-total-display", "children"),
    State({"type": "form-input", "id": ALL}, "id"),
    State({"type": "form-upload", "id": ALL}, "id")
)
def validate_form_and_payment(input_values, upload_contents, selected_division, disclaimer_val, fee_str, input_ids, upload_ids):
    # 1. Parse total numerical fee
    try:
        amount = float(str(fee_str).replace("$", "").strip())
    except (ValueError, TypeError, AttributeError):
        amount = 0.0

    # 2. Map inputs and upload contents by ID
    input_map = {item["id"]: val for item, val in zip(input_ids, input_values)}
    upload_map = {item["id"]: val for item, val in zip(upload_ids, upload_contents)}

    missing_reasons = []

    # 3. Check mandatory form fields from EVENT_CONFIG
    for field in EVENT_CONFIG.get("form_fields", []):
        if field.get("required"):
            fid = field["id"]
            if field.get("type") == "file":
                if not upload_map.get(fid):
                    missing_reasons.append(f"Upload {field['label']}")
            else:
                val = input_map.get(fid)
                if val is None or str(val).strip() == "":
                    missing_reasons.append(f"Fill out '{field['label']}'")

    # 4. Check Division Selection
    if not selected_division:
        missing_reasons.append("Select a Division")

    # 5. Check Rules & Disclaimer Agreement
    disclaimer_cfg = EVENT_CONFIG.get("disclaimer")
    if disclaimer_cfg:
        disclaimer_agreed = False
        if isinstance(disclaimer_val, list):
            disclaimer_agreed = len(disclaimer_val) > 0
        elif isinstance(disclaimer_val, str):
            disclaimer_agreed = disclaimer_val.strip() != ""
        if not disclaimer_agreed:
            missing_reasons.append("Agree to the Rules & Disclaimer")

    is_valid = len(missing_reasons) == 0

    # 6. Generate dynamic status banner UI
    if is_valid:
        notice = html.Div([
            html.Div("✓ Application Complete", className="badge bg-success mb-2 p-2 w-100 fs-6"),
            html.P("Complete payment below via PayPal or Card to finalize entry.", className="small text-white-50 mb-0")
        ])
    else:
        notice = html.Div(className="p-3 bg-dark bg-opacity-50 border border-warning rounded text-start", children=[
            html.Div("⚠️ Payment Locked", className="fw-bold text-warning small mb-1"),
            html.P("Complete the following to unlock payment:", className="small text-white-50 mb-1"),
            html.Ul(
                [html.Li(r, className="small text-white-50") for r in missing_reasons],
                className="mb-0 ps-3"
            )
        ])

    return {"is_valid": is_valid, "amount": amount}, notice

@app.callback(
    Output({"type": "upload-status", "id": MATCH}, "children"),
    Input({"type": "form-upload", "id": MATCH}, "filename"),
    prevent_initial_call=True
)
def update_upload_status(filename):
    if filename:
        return html.Span([
            "✅ File Attached: ",
            html.Strong(filename)
        ], style={"color": "#198754"})
    return "No file selected."

# --- VIEW TOGGLE & FORM RESET CALLBACKS ---

@app.callback(
    Output("form-and-checkout-row", "style"),
    Output("success-reset-row", "style"),
    Input("transaction-completed-store", "data")
)
def toggle_registration_view(is_completed):
    if is_completed:
        return {"display": "none"}, {"display": "block"}
    return {"display": "flex"}, {"display": "none"}

@app.callback(
    Output("transaction-completed-store", "data", allow_duplicate=True),
    Output({"type": "form-input", "id": ALL}, "value"),
    Output({"type": "form-upload", "id": ALL}, "contents"),
    Output("division-select", "value"),
    Output({'type': 'addon-select', 'index': ALL}, 'value'),
    Output("disclaimer-agreement", "value"),
    Input("reset-registration-btn", "n_clicks"),
    State({"type": "form-input", "id": ALL}, "id"),
    State({"type": "form-upload", "id": ALL}, "id"),
    State({'type': 'addon-select', 'index': ALL}, 'id'),
    prevent_initial_call=True
)
def reset_form_and_view(n_clicks, form_input_ids, upload_ids, addon_ids):
    # 1. Reset all dynamic form inputs
    reset_inputs = [None] * len(form_input_ids)

    # 2. Reset uploaded files
    reset_uploads = [None] * len(upload_ids)

    # 3. Reset division dropdown to initial selection
    default_division = EVENT_CONFIG["divisions"][0]["label"] if EVENT_CONFIG.get("divisions") else None

    # 4. Reset optional category radio choices to default selections
    default_addons = []
    for addon in EVENT_CONFIG.get("addons", []):
        default_val = addon["options"][0]["label"] if addon.get("options") else None
        for opt in addon.get("options", []):
            if opt["label"].lower() in ["no", "none", "no thanks", "i do not wish to enter"]:
                default_val = opt["label"]
                break
        default_addons.append(default_val)

    # 5. Clear disclaimer agreement
    reset_disclaimer = None

    return False, reset_inputs, reset_uploads, default_division, default_addons, reset_disclaimer

@app.callback(
    Output("transaction-completed-store", "data", allow_duplicate=True),
    Input("paypal-transaction-store", "data"),
    State({"type": "form-input", "id": ALL}, "value"),
    State({"type": "form-upload", "id": ALL}, "contents"),
    State("division-select", "value"),
    State({'type': 'addon-select', 'index': ALL}, 'value'),
    State("disclaimer-agreement", "value"),
    State({"type": "form-input", "id": ALL}, "id"),
    State({"type": "form-upload", "id": ALL}, "id"),
    prevent_initial_call=True
)
def handle_payment_success(trans_data, input_values, upload_contents, selected_division, selected_addons, disclaimer_val, input_ids, upload_ids):
    if not trans_data:
        return False

    input_map = {item["id"]: val for item, val in zip(input_ids, input_values)}
    upload_map = {item["id"]: val for item, val in zip(upload_ids, upload_contents)}

    # Save to Google Sheet & Drive
    save_registration_to_sheet(
        transaction_details=trans_data,
        form_input_data=input_map,
        upload_data=upload_map,
        selected_division=selected_division,
        selected_addons=selected_addons,
        disclaimer_val=disclaimer_val
    )

    return True

# ---- GOOGLE SERVICES API HELPER FUNCTIONS ----
def get_authorized_http(creds):
    """Configures httplib2 to route through PythonAnywhere proxy if environment variables are present."""
    proxy_url = (
        os.environ.get("http_proxy")
        or os.environ.get("https_proxy")
        or os.environ.get("HTTP_PROXY")
        or os.environ.get("HTTPS_PROXY")
    )

    if proxy_url:
        proxy_info = httplib2.proxy_info_from_url(proxy_url)
        http_client = httplib2.Http(proxy_info=proxy_info)
    else:
        http_client = httplib2.Http()

    return google_auth_httplib2.AuthorizedHttp(creds, http=http_client)

def get_google_services():
    service_account_file = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if not service_account_file or not os.path.exists(service_account_file):
        print("ERROR: Service account credentials file missing.")
        return None, None
    creds = service_account.Credentials.from_service_account_file(service_account_file, scopes=GOOGLE_SCOPES)
    authorized_http = get_authorized_http(creds)
    drive_service = build("drive", "v3", http=authorized_http)
    sheets_service = build("sheets", "v4", http=authorized_http)
    return drive_service, sheets_service

def upload_headshot_to_drive(drive_service, folder_id, base64_contents, contestant_name):
    """Decodes base64 upload and uploads image to Google Drive folder."""
    try:
        header, content = base64_contents.split(",")
        file_bytes = base64.b64decode(content)

        filename = f"{sanitize_id(contestant_name)}_headshot.jpg"
        media = MediaIoBaseUpload(io.BytesIO(file_bytes), mimetype="image/jpeg", resumable=True)

        file_metadata = {
            "name": filename,
            "parents": [folder_id]
        }

        uploaded_file = drive_service.files().create(
            body=file_metadata,
            media_body=media,
            fields="id, webViewLink",
            supportsAllDrives=True
        ).execute()

        # Set permissions so anyone with link can view image in Google Sheet
        drive_service.permissions().create(
            fileId=uploaded_file["id"],
            body={"role": "reader", "type": "anyone"},
            supportsAllDrives=True
        ).execute()

        return uploaded_file.get("webViewLink", "")
    except Exception as e:
        print(f"Error uploading headshot to Drive: {e}")
        return "Upload Failed"

def save_registration_to_sheet(transaction_details, form_input_data, upload_data, selected_division, selected_addons, disclaimer_val):
    """Formats submission payload and appends a row to the Google Sheet."""
    drive_service, sheets_service = get_google_services()
    if not drive_service or not sheets_service:
        return False

    spreadsheet_id = EVENT_CONFIG.get("spreadsheet_id")
    headshot_folder_id = EVENT_CONFIG.get("headshot_folder_id")
    headers = EVENT_CONFIG.get("sheet_headers", [])

    if not spreadsheet_id:
        print("ERROR: spreadsheet_id missing in config.json")
        return False

    # Extract Contestant Name for file naming
    contestant_name = "Contestant"
    for fid, val in form_input_data.items():
        if "name" in fid.lower() and val:
            contestant_name = str(val)
            break

    # Upload Headshot to Drive
    headshot_url = ""
    for fid, contents in upload_data.items():
        if fid == "headshot_upload" and contents:
            headshot_url = upload_headshot_to_drive(drive_service, headshot_folder_id, contents, contestant_name)

    # Build row mapping based on headers
    row_map = {
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Transaction ID": transaction_details.get("orderID", "N/A"),
        "Amount Paid": f"${transaction_details.get('amount', '0.00')}",
        "Division": selected_division or "",
        "Disclaimer Agreed": "Yes" if disclaimer_val else "No",
        "Headshot Image Link": headshot_url
    }

    # Add dynamic form fields
    for field in EVENT_CONFIG.get("form_fields", []):
        fid = field["id"]
        if fid != "headshot_upload":
            row_map[field["label"]] = form_input_data.get(fid, "")

    # Add dynamic add-ons
    addons_config = EVENT_CONFIG.get("addons", [])
    if selected_addons and len(selected_addons) == len(addons_config):
        for addon_group, selected_val in zip(addons_config, selected_addons):
            row_map[f"Add-On: {addon_group['title']}"] = selected_val or ""

    # Assemble row matching exact column order in Google Sheet
    row_values = [row_map.get(col, "") for col in headers]

    try:
        sheets_service.spreadsheets().values().append(
            spreadsheetId=spreadsheet_id,
            range="A1",
            valueInputOption="USER_ENTERED",
            insertDataOption="INSERT_ROWS",
            body={"values": [row_values]}
        ).execute()
        print("Successfully saved registration to Google Sheet!")
        return True
    except Exception as e:
        print(f"Error appending row to Google Sheet: {e}")
        return False

# --- CLIENTSIDE CALLBACK: CONDITIONALLY MOUNT PAYPAL ---

app.clientside_callback(
    ClientsideFunction(
        namespace="clientside",
        function_name="mountPayPal"
    ),
    Output("paypal-mount-status", "children"),
    Input("payment-validation-store", "data")
)

if __name__ == "__main__":
    app.run(debug=True)