import json
import os
import dash
from dotenv import load_dotenv
from dash import html, dcc, Input, Output, ALL, State

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(BASE_DIR, "assets", "config.json")
dotenv_path = os.path.join(BASE_DIR, "secrets", ".env")
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)
IS_PRODUCTION = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS") is not None
PATH_PREFIX = "/pageant/" if IS_PRODUCTION else "/"

# Load configuration generated by update_event.py
def load_config():
    config_path = os.path.join("assets", "config.json")
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "title": "MT Pockets Pageant Registration",
        "description": "",
        "base_fee": 50.0,
        "flyer_image": "flyer.jpg",
        "info_sections": [],
        "divisions": [],
        "addons": [],
        "form_fields": [],
        "disclaimer": None
    }

# Load configuration with fallback
EVENT_CONFIG = {}
if os.path.exists(CONFIG_PATH):
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        EVENT_CONFIG = json.load(f)
else:
    print(f"WARNING: Configuration file not found at {CONFIG_PATH}")

# PayPal Client ID ('test' for sandbox, or your live client ID)
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID", "test")

app = dash.Dash(
    __name__,
    requests_pathname_prefix=PATH_PREFIX,
    routes_pathname_prefix='/',
    external_stylesheets=[
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    ],
    external_scripts=[
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
        f"https://www.paypal.com/sdk/js?client-id={PAYPAL_CLIENT_ID}&currency=USD"
    ]
)

server = app.server

app.title = EVENT_CONFIG.get("title", "MT Pockets Pageant Registration")

# --- HELPER RENDER FUNCTIONS ---

def render_event_info(config):
    """Renders info_sections with the first section expanded by default."""
    info_sections = config.get("info_sections", [])
    if info_sections:
        accordion_items = []
        for idx, sec in enumerate(info_sections):
            accordion_items.append(
                html.Details(
                    className="mb-2 border rounded overflow-hidden bg-white shadow-sm",
                    open=(idx == 0),  # General Information / 1st section starts OPEN
                    children=[
                        html.Summary(
                            sec.get("title", f"Section {idx+1}"),
                            className="fw-bold p-3 bg-light text-dark",
                            style={"cursor": "pointer", "userSelect": "none"}
                        ),
                        html.Div(
                            sec.get("content", ""),
                            className="p-3 border-top",
                            style={"whiteSpace": "pre-line", "lineHeight": "1.6"}
                        )
                    ]
                )
            )
        return html.Div(className="accordion-container", children=accordion_items)

    return html.Div(
        config.get("description", ""),
        style={"whiteSpace": "pre-line", "lineHeight": "1.6"}
    )

def render_dynamic_form_fields(fields):
    """Renders contestant detail input fields using pattern-matching IDs for validation."""
    components = []
    for f in fields:
        label_text = f"{f['label']} *" if f.get("required") else f['label']
        field_children = [
            html.Label(label_text, className="form-label fw-bold mt-2"),
        ]

        if f.get("description"):
            field_children.append(html.P(f["description"], className="small text-muted mb-1"))

        # Pattern-matching dict ID
        field_id = {'type': 'form-field', 'index': f['id']}

        # Derive a concise placeholder text if not explicitly provided
        clean_label = f['label'].split('(')[0].replace('*', '').strip()
        placeholder_text = f.get("placeholder", f"Enter {clean_label}...")

        if f.get("type") == "text":
            field_children.append(
                dcc.Input(
                    id=field_id,
                    type="text",
                    className="form-control w-100",
                    style={"width": "100%"},
                    placeholder=placeholder_text))
        elif f.get("type") == "textarea":
            field_children.append(
                dcc.Textarea(
                    id=field_id,
                    className="form-control w-100",
                    style={"width": "100%"},
                    rows=3,
                    placeholder=placeholder_text))
        elif f.get("type") in ["dropdown", "radio"]:
            field_children.append(
                dcc.Dropdown(
                    id=field_id,
                    options=[{"label": opt, "value": opt} for opt in f.get("options", [])],
                    clearable=not f.get("required", False),
                    className="w-100",
                    style={"width": "100%"},
                    placeholder=f"Select {clean_label}..."
                )
            )

        components.append(html.Div(className="mb-3", children=field_children))

    return components

def render_addons_section(addons):
    """Renders optional categories (Themewear, Talent, Photogenic, etc.)"""
    if not addons:
        return None

    addon_cards = []
    for addon in addons:
        options_list = [
            {"label": f" {opt['label']}", "value": opt['label']}
            for opt in addon.get("options", [])
        ]

        default_val = addon["options"][0]["label"] if addon.get("options") else None
        for opt in addon.get("options", []):
            if opt["label"].lower() in ["no", "none", "no thanks", "i do not wish to enter"]:
                default_val = opt["label"]
                break

        addon_cards.append(
            html.Div(className="mb-4 pb-3 border-bottom", children=[
                html.H6(addon.get("title", "").split("\n")[0], className="fw-bold text-dark mb-1"),
                html.P(addon.get("description"), className="small text-muted mb-2", style={"whiteSpace": "pre-line"}),
                dcc.RadioItems(
                    id={'type': 'addon-select', 'index': addon.get("id", sanitize_id(addon.get("title", "")))},
                    options=options_list,
                    value=default_val,
                    className="custom-radio-group"
                )
            ])
        )

    return html.Div(className="card card-custom mb-4", children=[
        html.Div(className="card-header card-header-secondary", children=[
            html.H5("Optional Categories & Add-Ons", className="mb-0 fs-5")
        ]),
        html.Div(className="card-body", children=addon_cards)
    ])

def render_disclaimer(disclaimer_data):
    """Renders rules & disclaimer agreement card"""
    if not disclaimer_data:
        return None

    raw_title = disclaimer_data.get("title", "")
    text = disclaimer_data.get("text", "")

    if not raw_title or len(raw_title) > 80 or "\n" in raw_title or raw_title == text:
        header_title = "Pageant Rules & Sportsmanship Disclaimer"
    else:
        header_title = raw_title

    return html.Div(className="card card-custom disclaimer-card mb-4", children=[
        html.Div(className="card-header card-header-disclaimer p-3", children=[
            html.H5(header_title, className="mb-0 fs-5")
        ]),
        html.Div(className="card-body", children=[
            html.Div(
                text,
                className="disclaimer-full-text mb-3",
                style={"whiteSpace": "pre-line"}
            ),
            dcc.RadioItems(
                id=disclaimer_data.get("id", "disclaimer-agreement"),
                options=[{"label": f" {opt}", "value": opt} for opt in disclaimer_data.get("options", [])],
                className="custom-radio-group"
            )
        ])
    ])

def sanitize_id(title):
    import re
    clean = re.sub(r'[^a-zA-Z0-9\s]', '', title).strip().lower()
    return re.sub(r'\s+', '_', clean)

# --- APP LAYOUT ---

app.layout = html.Div(children=[

    # Form Validation State Store
    dcc.Store(id="payment-validation-store"),

    # 1. Header Banner
    html.Div(className="pageant-header text-center mb-4 py-4", children=[
        html.Div(className="container", children=[
            html.H1(EVENT_CONFIG.get("title", "Pageant Registration"), className="display-6 fw-bold mb-1"),
            html.P("M.T. Pockets Theatre, Inc. Fundraiser Registration", className="lead mb-0")
        ])
    ]),

    html.Div(className="container pb-5", children=[

        # 2. Hero Section: Flyer + Event Details Accordion
        html.Div(className="row g-4 mb-5", children=[
            html.Div(className="col-lg-5", children=[
                html.Div(className="flyer-card", children=[
                    html.Img(
                        src=app.get_asset_url(EVENT_CONFIG.get("flyer_image", "flyer.jpg")),
                        className="flyer-img",
                        alt="Event Flyer"
                    )
                ])
            ]),
            html.Div(className="col-lg-7", children=[
                html.Div(className="card card-custom h-100", children=[
                    html.Div(className="card-header card-header-primary", children=[
                        html.H5("Event Details & Information", className="mb-0 fs-5")
                    ]),
                    html.Div(className="card-body event-description-box", children=[
                        render_event_info(EVENT_CONFIG)
                    ])
                ])
            ])
        ]),

        # 3. Main Registration & Checkout Section
        html.Div(className="row g-4", children=[

            # Left Column (lg-8): Form
            html.Div(className="col-lg-8", children=[

                # Participant Details Card
                html.Div(className="card card-custom mb-4", children=[
                    html.Div(className="card-header card-header-primary", children=[
                        html.H5("1. Contestant & Contact Information", className="mb-0 fs-5")
                    ]),
                    html.Div(className="card-body", children=render_dynamic_form_fields(EVENT_CONFIG.get("form_fields", [])))
                ]),

                # Age Division Selection Card
                html.Div(className="card card-custom mb-4", children=[
                    html.Div(className="card-header card-header-primary", children=[
                        html.H5("2. Select Age Division *", className="mb-0 fs-5")
                    ]),
                    html.Div(className="card-body", children=[
                        html.P(f"Main Event Entry Fee: ${EVENT_CONFIG.get('base_fee', 50.0):.2f}", className="small fw-bold text-muted mb-2"),
                        dcc.Dropdown(
                            id="division-select",
                            options=[
                                {"label": f"{div['label']} — ${div['price']:.2f}", "value": div['label']}
                                for div in EVENT_CONFIG.get("divisions", [])
                            ],
                            value=EVENT_CONFIG["divisions"][0]["label"] if EVENT_CONFIG.get("divisions") else None,
                            clearable=False,
                            className="form-select-lg"
                        )
                    ])
                ]),

                # Optional Add-Ons Section
                render_addons_section(EVENT_CONFIG.get("addons", [])),

                # Rules & Disclaimer Agreement Card
                render_disclaimer(EVENT_CONFIG.get("disclaimer"))
            ]),

            # Right Column (lg-4): Sticky Checkout Summary & Payment
            html.Div(className="col-lg-4", children=[
                html.Div(className="sticky-top", style={"top": "20px"}, children=[
                    html.Div(className="card checkout-card p-4 text-center mb-3", children=[
                        html.H5("Registration Summary", className="text-uppercase tracking-wide text-white-50 mb-2 fs-6"),

                        # Fee Breakdown Output
                        html.Div(id="fee-breakdown-display", className="text-start mb-3 small text-white-50 border-bottom border-secondary pb-2"),

                        # Fee Total Display
                        html.Div("Total Amount Due", className="small text-uppercase text-white-50 fw-semibold"),
                        html.Div(id="fee-total-display", className="total-amount-display my-1", children="$50.00"),

                        # Dynamic Status Banner
                        html.Div(id="payment-notice-display", className="my-3"),

                        # Mount Point for PayPal Smart Payment Buttons
                        html.Div(id="paypal-button-container", style={"minHeight": "150px"}),

                        # Hidden Status Output for Clientside Callback
                        html.Div(id="paypal-mount-status", style={"display": "none"})
                    ]),

                    html.Div(className="text-center text-muted small", children=[
                        "M.T. Pockets Theatre, Inc. is a registered 501(c)(3) non-profit organization."
                    ])
                ])
            ])
        ])
    ])
])

# --- DYNAMIC FEE CALCULATION CALLBACK ---

@app.callback(
    Output("fee-total-display", "children"),
    Output("fee-breakdown-display", "children"),
    Input("division-select", "value"),
    Input({'type': 'addon-select', 'index': ALL}, 'value')
)
def calculate_total_fee(selected_division, selected_addons):
    total = 0.0
    breakdown_items = []

    for div in EVENT_CONFIG.get("divisions", []):
        if div["label"] == selected_division:
            total += div["price"]
            breakdown_items.append(
                html.Div(className="d-flex justify-content-between mb-1", children=[
                    html.Span(f"Main Event ({selected_division}):", className="text-truncate me-2"),
                    html.Span(f"${div['price']:.2f}", className="fw-bold text-white")
                ])
            )
            break

    addons_config = EVENT_CONFIG.get("addons", [])
    if selected_addons and len(selected_addons) == len(addons_config):
        for addon_group, selected_val in zip(addons_config, selected_addons):
            if not selected_val:
                continue
            for opt in addon_group.get("options", []):
                if opt["label"] == selected_val:
                    if opt.get("price", 0) > 0:
                        total += opt["price"]
                        short_title = addon_group.get("title", "").split("\n")[0]
                        breakdown_items.append(
                            html.Div(className="d-flex justify-content-between mb-1", children=[
                                html.Span(f"{short_title}:", className="text-truncate me-2", style={"maxWidth": "180px"}),
                                html.Span(f"${opt['price']:.2f}", className="fw-bold text-white")
                            ])
                        )
                    break

    return f"${total:.2f}", breakdown_items

# --- FORM & DISCLAIMER VALIDATION CALLBACK ---

disclaimer_cfg = EVENT_CONFIG.get("disclaimer")
disclaimer_id = disclaimer_cfg.get("id", "disclaimer-agreement") if disclaimer_cfg else None

validation_inputs = [
    Input({'type': 'form-field', 'index': ALL}, 'value'),
    Input({'type': 'form-field', 'index': ALL}, 'id'),
    Input("fee-total-display", "children")
]
if disclaimer_id:
    validation_inputs.insert(2, Input(disclaimer_id, 'value'))

@app.callback(
    Output("payment-validation-store", "data"),
    Output("payment-notice-display", "children"),
    *validation_inputs
)
def validate_form_and_payment(*args):
    field_values = args[0]
    field_ids = args[1]

    if disclaimer_id:
        disclaimer_val = args[2]
        fee_str = args[3]
    else:
        disclaimer_val = None
        fee_str = args[2]

    # 1. Extract total numerical amount
    try:
        amount = float(str(fee_str).replace("$", "").strip())
    except (ValueError, AttributeError):
        amount = 0.0

    # 2. Map field inputs to check required fields
    val_map = {fid['index']: val for fid, val in zip(field_ids, field_values)}
    missing_required = False

    for f in EVENT_CONFIG.get("form_fields", []):
        if f.get("required"):
            val = val_map.get(f['id'])
            if val is None or str(val).strip() == "":
                missing_required = True
                break

    # 3. Check disclaimer agreement match
    disclaimer_agreed = True
    if disclaimer_cfg:
        disclaimer_agreed = (disclaimer_val == "I agree to the above statement")

    is_valid = (not missing_required) and disclaimer_agreed

    # 4. Generate dynamic status banner UI
    if is_valid:
        notice = html.Div([
            html.Div("✓ Application Complete", className="badge bg-success mb-2 p-2 w-100 fs-6"),
            html.P("Complete payment below via PayPal or Card to finalize entry.", className="small text-white-50 mb-0")
        ])
    else:
        reasons = []
        if missing_required:
            reasons.append("Fill out all required contestant fields")
        if disclaimer_cfg and not disclaimer_agreed:
            reasons.append("Select 'I agree to the above statement'")

        notice = html.Div(className="p-3 bg-dark bg-opacity-50 border border-warning rounded text-start", children=[
            html.Div("⚠️ Payment Locked", className="fw-bold text-warning small mb-1"),
            html.P("Complete the following to unlock payment:", className="small text-white-50 mb-1"),
            html.Ul(
                [html.Li(r, className="small text-white-50") for r in reasons],
                className="mb-0 ps-3"
            )
        ])

    return {"is_valid": is_valid, "amount": amount}, notice

# --- CLIENTSIDE CALLBACK: CONDITIONALLY MOUNT PAYPAL ---

app.clientside_callback(
    """
    function(validation_data) {
        const container = document.getElementById("paypal-button-container");
        if (!container) return "";
        
        // Clear container whenever validation status changes
        container.innerHTML = "";
        
        if (!validation_data || !validation_data.is_valid) {
            return "Payment Locked (Form Incomplete)";
        }
        
        if (!window.paypal) {
            console.warn("PayPal SDK not loaded.");
            return "PayPal SDK Missing";
        }
        
        const amount = parseFloat(validation_data.amount) || 0;
        if (amount <= 0) return "Invalid Amount";

        paypal.Buttons({
            style: {
                layout: 'vertical',
                color:  'gold',
                shape:  'rect',
                label:  'paypal'
            },
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: amount.toFixed(2)
                        }
                    }]
                });
            },
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    alert('Transaction completed by ' + details.payer.name.given_name + '! Registration confirmed.');
                });
            },
            onError: function(err) {
                console.error('PayPal Error:', err);
            }
        }).render('#paypal-button-container');
        
        return "PayPal Mounted ($" + amount.toFixed(2) + ")";
    }
    """,
    Output("paypal-mount-status", "children"),
    Input("payment-validation-store", "data")
)

if __name__ == "__main__":
    app.run(debug=True)